version: '1.0'
services:
  es_1:
    # 镜像名称
    image: elasticsearch:7.6.1
    # 容器名称
    container_name: es1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 文件映射到主机
    volumes:
      - /home/winner/docker/es/config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # 赋予权限
    privileged: true
    #端口映射
    ports:
      - 9200:9200
      - 9300:9300
    # 指定网段
    networks:
      es:
        ipv4_address: 173.199.8.2   #设置ip地址
  es_2:
    # 镜像名称
    image: elasticsearch:7.6.1
    # 容器名称
    container_name: es2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 文件映射到主机
    volumes:
      - /home/winner/docker/es/config/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # 赋予权限
    privileged: true
    #端口映射
    ports:
      - 9201:9200
      - 9301:9300
    # 指定网段
    networks:
      es:
        ipv4_address: 173.199.8.3   #设置ip地址
  es_3:
    # 镜像名称
    image: elasticsearch:7.6.1
    # 容器名称
    container_name: es3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 文件映射到主机
    volumes:
      - /home/winner/docker/es/config/es3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # 赋予权限
    privileged: true
    #端口映射
    ports:
      - 9202:9200
      - 9302:9300
    # 指定网段
    networks:
      es:
        ipv4_address: 173.199.8.4   #设置ip地址
networks:
  es:
    driver: bridge
    ipam:
      config:
        - subnet: "173.199.8.0/24"