#修改elasticsearch.hosts的地址, 改成es的ip
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: "http://nezha_user_es-1:9200"
xpack.monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: zh-CN #中文