version: '2.1'

networks:
  nezha_mq_net:
    external: true

services:

  nezha_mq_kafka1:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: nezha_mq_kafka1
    ports:
      - "9093:9092"
    external_links:
      - nezha_mq_zk1
      - nezha_mq_zk2
      - nezha_mq_zk3
    privileged: true
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: nezha_mq_kafka1                   ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9093                                 ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.130:9093    ## 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "nezha_mq_zk1:2181,nezha_mq_zk2:2181,nezha_mq_zk3:2181"
    volumes:
      - "./kafka/nezha_mq_kafka1/docker.sock:/var/run/docker.sock"
      - "./kafka/nezha_mq_kafka1/data/:/kafka"
    networks:
      - nezha_mq_net


  nezha_mq_kafka2:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: nezha_mq_kafka2
    ports:
      - "9094:9092"
    external_links:
      - nezha_mq_zk1
      - nezha_mq_zk2
      - nezha_mq_zk3
    privileged: true
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: nezha_mq_kafka2                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9094                               ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.130:9094   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "nezha_mq_zk1:2181,nezha_mq_zk2:2181,nezha_mq_zk3:2181"
    volumes:
      - "./kafka/nezha_mq_kafka2/docker.sock:/var/run/docker.sock"
      - "./kafka/nezha_mq_kafka2/data/:/kafka"
    networks:
      - nezha_mq_net

  nezha_mq_kafka3:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: nezha_mq_kafka3
    ports:
      - "9095:9092"
    external_links:
      - nezha_mq_zk1
      - nezha_mq_zk2
      - nezha_mq_zk3
    privileged: true
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: nezha_mq_kafka3              ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9095                              ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.130:9095   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "nezha_mq_zk1:2181,nezha_mq_zk2:2181,nezha_mq_zk3:2181"
    volumes:
      - "./kafka/nezha_mq_kafka3/docker.sock:/var/run/docker.sock"
      - "./kafka/nezha_mq_kafka3/data/:/kafka"
    networks:
      - nezha_mq_net

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9100:9000"
    links: # 连接本compose文件创建的container
      - nezha_mq_kafka1
      - nezha_mq_kafka2
      - nezha_mq_kafka3
    external_links: # 连接本compose文件以外的container
      - nezha_mq_zk1
      - nezha_mq_zk2
      - nezha_mq_zk3
    privileged: true
    environment:
      ZK_HOSTS: "nezha_mq_zk1:2181,nezha_mq_zk2:2181,nezha_mq_zk3:2181"
      TZ: CST-8
    networks:
      - nezha_mq_net