version: '2.1'

networks:
  nezha_mq_net:
    external: true

services:
  nezha_mq_zk1:
    image: zookeeper
    restart: unless-stopped
    hostname: nezha_mq_zk1
    container_name: nezha_mq_zk1
    # 赋予权限
    privileged: true
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=nezha_mq_zk2:2888:3888;2181 server.3=nezha_mq_zk3:2888:3888;2181
    volumes:
      - ./zookeeper/nezha_mq_zk1/data:/data
      - ./zookeeper/nezha_mq_zk1/datalog:/datalog
    networks:
      - nezha_mq_net

  nezha_mq_zk2:
    image: zookeeper
    restart: unless-stopped
    hostname: nezha_mq_zk2
    container_name: nezha_mq_zk2
      # 赋予权限
    privileged: true
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=nezha_mq_zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=nezha_mq_zk3:2888:3888;2181
    volumes:
      - ./zookeeper/nezha_mq_zk2/data:/data
      - ./zookeeper/nezha_mq_zk2/datalog:/datalog
    networks:
      - nezha_mq_net

  nezha_mq_zk3:
    image: zookeeper
    restart: unless-stopped
    hostname: nezha_mq_zk3
    container_name: nezha_mq_zk3
    # 赋予权限
    privileged: true
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=nezha_mq_zk1:2888:3888;2181 server.2=nezha_mq_zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./zookeeper/nezha_mq_zk3/data:/data
      - ./zookeeper/nezha_mq_zk3/datalog:/datalog
    networks:
      - nezha_mq_net