version: '3'

services:
  php:
    container_name: php
    image: php:8-fpm-alpine3.14
    tty: true
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
      - ./docker/config/ini:/usr/local/etc/php
    depends_on:
      - mysql
      - redis
    privileged: true
    links:
      - mysql:mysql
      - redis:redis
    command: docker-php-ext-install pdo_mysql sockets pcntl
    command: php-fpm -c /usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Shanghai
  nginx:
    container_name: nginx
    image: nginx:latest
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/www:/data/www
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/log/nginx:/var/log/nginx
    privileged: true
    depends_on: #设置依赖关系 先启动 php ，才会启动 nginx
      - php
    links:
      - php
    environment:
     - TZ=Asia/Shanghai
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql/data
      - ./docker/config/mysql:/etc/mysql/conf.d
      - ./docker/log/mysql:/var/lib/mysql/log
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nezha
      - MYSQL_PASSWORD=123546
      - TZ=Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: mysqld --defaults-file=/etc/mysql/conf.d/my.cnf

  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/usr/local/redis/data
      - ./docker/config/redis:/usr/local/redis/
    privileged: true
    command: redis-server /usr/local/redis/redis.conf --appendonly yes
    environment:
      - TZ=Asia/Shanghai

  phpmyadmin:
    container_name: phpmyadmin
    image: daocloud.io/daocloud/phpmyadmin
    expose:
      - '80'
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      # 如果取消下面两行注释, phpmyadmin就不用输入用户名和密码, 可以直接登录
      - PMA_USER=nezha
      - PMA_PASSWORD=nezha123
    depends_on:
      - mysql
    links:
      - mysql:mysql
  phpredisadmin:
    container_name: phpredisadmin
    image: erikdubbelboer/phpredisadmin
    expose:
      - '80'
    ports:
      - "8081:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=redis
    depends_on:
      - redis
    links:
      - redis:redis



