version: '3.2'
services:
  rabbitmq1:
    image: rabbitmq:3.7-management
    # 赋予权限
    privileged: true
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: nezha_user_rabbitmq1
    container_name: nezha_user_rabbitmq1
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      nezha_rab_net:
        ipv4_address: 173.14.0.2
    volumes:
      - /home/nezha/rabbitmq/rabbitmq1:/var/lib/rabbitmq
      - /home/nezha/rabbitmq/etc/localtime:/etc/localtime

  rabbitmq2:
    image: rabbitmq:3.7-management
    ports:
      - "5673:5672"
      - "15673:15672"
    hostname: nezha_user_rabbitmq2
    container_name: nezha_user_rabbitmq2
    restart: always
      # 赋予权限
    privileged: true
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      nezha_rab_net:
        ipv4_address: 173.14.0.3
    volumes:
      - /home/nezha/rabbitmq/rabbitmq2:/var/lib/rabbitmq
      - /home/nezha/rabbitmq/etc/localtime:/etc/localtime
    depends_on:
      - rabbitmq1
    links:
        - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3.7-management
    ports:
      - "5674:5672"
      - "15674:15672"
        # 赋予权限
    privileged: true
    hostname: nezha_user_rabbitmq3
    container_name: nezha_user_rabbitmq3
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      nezha_rab_net:
        ipv4_address: 173.14.0.4
    volumes:
      - /home/nezha/rabbitmq/rabbitmq3:/var/lib/rabbitmq
      - /home/nezha/rabbitmq/etc/localtime:/etc/localtime
    depends_on:
      - rabbitmq1
      - rabbitmq2
    links:
        - rabbitmq1

networks:
  nezha_rab_net:
    #引用容器外部网络 nezha_rab_net
    external:
      name: nezha_rab_net
  #  定义容器使用网名，无论有网络，都会进行创建。如果外部存在了相同的网络端，就会报错提示
  #  driver: bridge
  #  ipam:
  #    config:
  #      - subnet: "173.14.0.0/24"
